# Generated by Django 5.0.1 on 2024-02-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_accesslink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesslink",
            name="link_uuid",
            field=models.UUIDField(unique=True),
        ),
    ]
