# Generated by Django 5.0.1 on 2024-02-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_accesslink_link_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesslink",
            name="username",
            field=models.CharField(default="username", max_length=50, unique=True),
        ),
    ]
