# Generated by Django 5.0.1 on 2024-02-01 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_accesslink_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accesslink",
            old_name="link_uuid",
            new_name="access_token",
        ),
        migrations.RemoveField(
            model_name="accesslink",
            name="posts_owner",
        ),
    ]
