# Generated by Django 5.0.1 on 2024-02-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_rename_link_uuid_accesslink_access_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesslink",
            name="username",
            field=models.CharField(default="username", max_length=50),
        ),
    ]
