# Generated by Django 5.0.1 on 2024-02-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_accesslink_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesslink",
            name="name",
            field=models.CharField(default="name", max_length=100),
        ),
        migrations.AlterField(
            model_name="accesslink",
            name="access_token",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="accesslink",
            name="email",
            field=models.CharField(default="email", max_length=100),
        ),
    ]
