# Generated by Django 5.0.1 on 2024-01-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="file_type",
            field=models.CharField(default="image", max_length=50),
        ),
    ]
