# Generated by Django 5.0.1 on 2024-02-01 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0004_accesslink"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AccessLink",
        ),
    ]
